### ISSUE TITLE
Real-Time Content Editing Indicator for Umbraco

### ISSUE THREAD

**Issue by dKumarmj** [leekelleher/umbraco-package-ideas#49]
### Idea summary

This Umbraco package idea is to improve collaboration by showing who is actively editing content in real-time. When a user is logged in and editing a specific content item, an icon or indicator would appear at the top of the editing screen or in the content tree. This lets other editors know that someone is already working on that content, helping avoid conflicts or accidental overwrites.

This feature would make it easier for teams to work together seamlessly in Umbraco by showing clear, real-time updates on content activity.

### Which categories would the idea fit?

- [X] Back-office
- [ ] Developer Tools
- [ ] Front-end
- [ ] Starter Kits
- [ ] Misc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by LottePitcher** [comment]
Hey @dKumarmj - does this package do what you were proposing?

https://marketplace.umbraco.com/package/arjo.umbracobackofficeeditorview

**Comment by dKumarmj** [comment]
Oops! Looks like I had a déjà vu moment. Thanks @LottePitcher 😊, I don't have an idea about this, I'm late 😁
